/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ordermanagementsystem.order;

import javax.swing.JOptionPane;
import ordermanagementsystem.MainMenu;
import ordermanagementsystem.model.Customer;
import ordermanagementsystem.model.Item;
import ordermanagementsystem.model.OrderLine;
import ordermanagementsystem.model.SyzygyGroup;
import ordermanagementsystem.service.OrderService;

/**
 *
 * @author acer
 */
public class OrderManageAdmin extends javax.swing.JFrame {

    /**
     * Creates new form OrderManageAdmin
     */
    private final OrderService orderService;
    private ChatManagement chatManagement;

    public OrderManageAdmin() {
        initComponents();
        this.orderService = new OrderService();
        this.chatManagement = new ChatManagement();
        this.performFileRelatedTask();
    }

    private void performFileRelatedTask() {
        StringBuilder stringBuilder = new StringBuilder();
        int num = 1;
        for (OrderLine orderLine : orderService.getAllOrders()) {
            stringBuilder.append(num)
                    .append("\t\t")
                    .append(orderLine.getOrderID())
                    .append(" \t\t")
                    .append(orderLine.getName())
                    .append(" \t\t            ")
                    .append(orderLine.getToppings())
                    .append(" \t\t\t")
                    .append(orderLine.getQuantity())
                    .append(" \t\t")
                    .append(orderLine.getPrice())
                    .append("\n");
            num++;
        }
        reciptArea.setText(stringBuilder.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        reciptArea = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        completeOrderButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        reciptArea.setEditable(false);
        reciptArea.setBackground(new java.awt.Color(255, 153, 102));
        reciptArea.setColumns(20);
        reciptArea.setRows(5);
        jScrollPane2.setViewportView(reciptArea);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel8.setText("Price");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel7.setText("Quantity");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel10.setText("Name");

        completeOrderButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        completeOrderButton.setText("Complete");
        completeOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeOrderButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setText("ID");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton1.setText("Pack");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton2.setText("Cook");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton3.setText("Accept");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton5.setText("Chat");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setText("Toppings");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel1)
                .addGap(162, 162, 162)
                .addComponent(jLabel10)
                .addGap(173, 173, 173)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(165, 165, 165)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(completeOrderButton)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(completeOrderButton)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void completeOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeOrderButtonActionPerformed

        OrderHandler acceptHandler = new AcceptanceHandler();
        OrderHandler cookHandler = new CookingHandler();
        OrderHandler packHandler = new PackingHandler();
        OrderHandler completeHandler = new CompleteHandler();

        acceptHandler.setNext(cookHandler);
        cookHandler.setNext(packHandler);
        packHandler.setNext(completeHandler);

        acceptHandler.handleOrder(orderService.getFirstOrder(), this);

        SyzygyGroup syzygyGroup = new SyzygyGroup("Syzygy Group");

        ChatMediator chatMediator = new ChatMediator(syzygyGroup, chatManagement);
        syzygyGroup.setMediator(chatMediator);

        syzygyGroup.sendMessage("Your order is being completed. It will be delivered to your doorstep..");

        orderService.clearOrder();
        this.reciptArea.setText("");
        performFileRelatedTask();

        jButton3.setEnabled(true);
        jButton2.setEnabled(true);
        jButton1.setEnabled(true);
    }//GEN-LAST:event_completeOrderButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (jButton3.isEnabled()) {

            JOptionPane.showMessageDialog(this, "Order has been accepted.");

            SyzygyGroup syzygyGroup = new SyzygyGroup("Syzygy Group");

            ChatMediator chatMediator = new ChatMediator(syzygyGroup, chatManagement);
            syzygyGroup.setMediator(chatMediator);

            syzygyGroup.sendMessage("Your order has been accepted.");

            jButton3.setEnabled(false);
        } else {
            jButton3.setEnabled(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jButton2.isEnabled()) {

            JOptionPane.showMessageDialog(this, "Order is being cooked.");

            SyzygyGroup syzygyGroup = new SyzygyGroup("Syzygy Group");

            ChatMediator chatMediator = new ChatMediator(syzygyGroup, chatManagement);
            syzygyGroup.setMediator(chatMediator);

            syzygyGroup.sendMessage("Your order is being cooked.");

            jButton2.setEnabled(false);
        } else {
            jButton2.setEnabled(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jButton1.isEnabled()) {
            JOptionPane.showMessageDialog(this, "Order is being packed.");

            SyzygyGroup syzygyGroup = new SyzygyGroup("Syzygy Group");

            ChatMediator chatMediator = new ChatMediator(syzygyGroup, chatManagement);
            syzygyGroup.setMediator(chatMediator);

            syzygyGroup.sendMessage("Your order is being packed.");

            jButton1.setEnabled(false);
        } else {
            jButton1.setEnabled(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Chat im = new Chat();
        im.setUser(new SyzygyGroup("Syzygy Group"));
        im.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        MainMenu im = new MainMenu();
        im.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    public javax.swing.JButton getjBtn3() {

        return jButton3;
    }

    public javax.swing.JButton getjBtn2() {

        return jButton2;
    }

    public javax.swing.JButton getjBtn1() {

        return jButton1;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderManageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderManageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderManageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderManageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderManageAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton completeOrderButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea reciptArea;
    // End of variables declaration//GEN-END:variables
}

interface OrderHandler {

    void handleOrder(OrderLine order, OrderManageAdmin orderManageAdmin);

    void setNext(OrderHandler next);
}

// Concrete Handler
class AcceptanceHandler implements OrderHandler {

    private OrderHandler next;

    @Override
    public void handleOrder(OrderLine order, OrderManageAdmin orderManageAdmin) {

        if (next != null && orderManageAdmin.getjBtn3().isEnabled() == false) {
            next.handleOrder(order, orderManageAdmin);
        } else {
            JOptionPane.showMessageDialog(orderManageAdmin, "Order has not been accepted.");
            System.out.println("No handler available for this order status.");
        }
    }

    @Override
    public void setNext(OrderHandler next) {
        this.next = next;
    }
}

// Concrete Handler
class CookingHandler implements OrderHandler {

    private OrderHandler next;

    @Override
    public void handleOrder(OrderLine order, OrderManageAdmin orderManageAdmin) {

        if (next != null && orderManageAdmin.getjBtn3().isEnabled() == false) {
            next.handleOrder(order, orderManageAdmin);
        } else {
            JOptionPane.showMessageDialog(orderManageAdmin, "Order is not being cooked.");
            System.out.println("No handler available for this order status.");
        }
    }

    @Override
    public void setNext(OrderHandler next) {
        this.next = next;
    }
}

// Concrete Handler
class PackingHandler implements OrderHandler {

    private OrderHandler next;

    @Override
    public void handleOrder(OrderLine order, OrderManageAdmin orderManageAdmin) {

        if (next != null && orderManageAdmin.getjBtn3().isEnabled() == false) {
            next.handleOrder(order, orderManageAdmin);
        } else {
            JOptionPane.showMessageDialog(orderManageAdmin, "Order is not being packed.");
            System.out.println("No handler available for this order status.");
        }
    }

    @Override
    public void setNext(OrderHandler next) {
        this.next = next;
    }
}

class CompleteHandler implements OrderHandler {

    private OrderHandler next;

    @Override
    public void handleOrder(OrderLine order, OrderManageAdmin orderManageAdmin) {
        JOptionPane.showMessageDialog(orderManageAdmin, "Order is being completed.");

        if (next != null) {
            next.handleOrder(order, orderManageAdmin);
        }
    }

    @Override
    public void setNext(OrderHandler next) {
        this.next = next;
    }
}
